In [1]:
import unittest
import numpy as np
from qiskit import QuantumCircuit, execute, Aer, IBMQ, QuantumRegister, ClassicalRegister
from qiskit.transpiler import PassManager
from qiskit.converters import circuit_to_dag, dag_to_circuit
from qiskit.compiler import transpile, assemble
from qiskit.tools.jupyter import *
from qiskit.visualization import *
import qiskit
from qiskit.tools.visualization import dag_drawer
import pyzx as zx
import fractions
from copy import copy
from qiskit.transpiler.basepasses import TransformationPass
from qiskit.transpiler import Layout
from qiskit.circuit.library import SwapGate
from typing import List, Callable, Optional, Union
from qiskit.test import QiskitTestCase

In [2]:
from ZX_to_DAG import zx_to_dag, get_unitary_matrix,matrix_equality
# from Pass_ZX_to_dag import ZX_dag_pass

In [4]:
qc=QuantumCircuit(3)
qc.h(0)
qc.cx(0,1)
qc.cx(0,2)

In [5]:
simulator = Aer.get_backend('aer_simulator')
qc1 = transpile(qc, simulator,optimization_level=0,basis_gates=['u3','cx'])

In [6]:
g=zx.qasm(qc1.qasm())

In [7]:
mat1=get_unitary_matrix(qc1)

In [8]:
d=zx_to_dag(g)

y2
HAD(0)
CNOT(0,1)
CNOT(0,2)


In [9]:
g

Circuit(3 qubits, 0 bits, 7 gates)

In [10]:
from copy import copy
from qiskit.transpiler.basepasses import TransformationPass
from qiskit.transpiler import Layout
from qiskit.circuit.library import SwapGate
from typing import List, Callable, Optional, Union
import qiskit
import pyzx as zx
from ZX_to_DAG import zx_to_dag, get_unitary_matrix

class ZXSwap(TransformationPass):
    """converts from ZX diagrams to Qiskit DAG circuits and DAGs to ZX diagrams"""

    def run(self, obj: Union[qiskit.circuit.quantumcircuit.QuantumCircuit,zx.graph.graph_s.GraphS, zx.circuit.Circuit,
                            qiskit.dagcircuit.dagcircuit.DAGCircuit]):
        
        """
        Args:
            obj: Could be ZX circuits or spiders/diagrams or qiskit circuits or qiskit DAGs
        """
        
        if (isinstance(obj,qiskit.circuit.quantumcircuit.QuantumCircuit) or isinstance(obj,qiskit.dagcircuit.dagcircuit.DAGCircuit)):
            print('to be added soon')
        
        if (isinstance(obj,zx.graph.graph_s.GraphS) or isinstance(obj,zx.circuit.Circuit)):
            dag=zx_to_dag(obj)

        return dag

In [11]:
obj = ZXSwap()

In [12]:
obj.run(g)

y2
HAD(0)
CNOT(0,1)
CNOT(0,2)


In [14]:
# obj = ZX_dag_pass.ZX_dag_pass()
# d1=obj.run(g)

In [15]:
qc2=dag_to_circuit(d)

In [16]:
mat2=get_unitary_matrix(qc2)

In [17]:
mat1

array([[ 0.70710678+0.j,  0.70710678-0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j],
       [ 0.        +0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j,  0.        +0.j,
         0.70710678+0.j, -0.70710678+0.j],
       [ 0.        +0.j,  0.        +0.j,  0.70710678+0.j,
         0.70710678-0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j],
       [ 0.        +0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.70710678+0.j, -0.70710678+0.j,
         0.        +0.j,  0.        +0.j],
       [ 0.        +0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.70710678+0.j,  0.70710678-0.j,
         0.        +0.j,  0.        +0.j],
       [ 0.        +0.j,  0.        +0.j,  0.70710678+0.j,
        -0.70710678+0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j],
       [ 0.        +0.j,  0.      

In [18]:
mat2

array([[ 0.70710678+0.j,  0.70710678-0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j],
       [ 0.        +0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j,  0.        +0.j,
         0.70710678+0.j, -0.70710678+0.j],
       [ 0.        +0.j,  0.        +0.j,  0.70710678+0.j,
         0.70710678-0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j],
       [ 0.        +0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.70710678+0.j, -0.70710678+0.j,
         0.        +0.j,  0.        +0.j],
       [ 0.        +0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.70710678+0.j,  0.70710678-0.j,
         0.        +0.j,  0.        +0.j],
       [ 0.        +0.j,  0.        +0.j,  0.70710678+0.j,
        -0.70710678+0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j,  0.        +0.j],
       [ 0.        +0.j,  0.      

In [19]:
mat1_arr = np.reshape(mat1,mat1.size)

In [20]:
mat2_arr = np.reshape(mat2,mat2.size)

In [21]:
(mat1_arr!=0).argmax(axis=0)

0

In [22]:
arr=np.array([0,0,1,5,6,7])
(arr!=0).argmax(axis=0)

2

In [23]:
first_non_zero_ind = (mat1_arr!=0).argmax(axis=0)
possible_scalar = (mat1_arr[first_non_zero_ind])/(mat2_arr[first_non_zero_ind])

In [24]:
possible_scalar

(1+0j)

In [25]:
len(range(first_non_zero_ind))

0

In [26]:
[True]*len(range(first_non_zero_ind))

[]

In [27]:
li1=[True]*len(range(2))

In [28]:
li1

[True, True]

In [29]:
li1.append(True)

In [30]:
li1

[True, True, True]

In [31]:
first_non_zero_ind = (mat1_arr!=0).argmax(axis=0)
bool_list=[True]*len(range(first_non_zero_ind))
possible_scalar = (mat1_arr[first_non_zero_ind])/(mat2_arr[first_non_zero_ind])
for i in range(mat1_arr.size):
    if (mat1_arr[i]==0 and mat2_arr[i]==0):
        bool_list.append(True)
    if (mat1_arr[i]!=0 and mat2_arr[i]!=0):
        new_sca=(mat1_arr[i])/(mat2_arr[i])
        if (np.isclose(possible_scalar.imag,new_sca.imag) and np.isclose(possible_scalar.real,new_sca.real)):
            bool_list.append(True)        

In [32]:
len(bool_list)

64

In [33]:
class TestZXtoDAG(QiskitTestCase):
    """Test for 1q gate optimizations."""

    def test_GHZ(self):
        """Identity gates are like 'wait' commands.
        They should never be optimized (even without barriers).
        See: https://github.com/Qiskit/qiskit-terra/issues/2373
        """
        qc=QuantumCircuit(3)
        qc.h(0)
        qc.cx(0,1)
        qc.cx(0,2)
        
        #convert to zx circuit
        simulator = Aer.get_backend('aer_simulator')
        qc1 = transpile(qc, simulator,optimization_level=0,basis_gates=['u3','cx'])

        g=zx.qasm(qc1.qasm())
        mat1=get_unitary_matrix(qc1)
        d=zx_to_dag(g)
        
        qc2=dag_to_circuit(d)

        mat2=get_unitary_matrix(qc2)
        
        mat1_arr = np.reshape(mat1,mat1.size)
        mat2_arr = np.reshape(mat2,mat2.size)
        first_non_zero_ind = (mat1_arr!=0).argmax(axis=0)
        bool_list=[True]*len(range(first_non_zero_ind))
        possible_scalar = (mat1_arr[first_non_zero_ind])/(mat2_arr[first_non_zero_ind])
        for i in range(mat1_arr.size):
            if (mat1_arr[i]==0 and mat2_arr[i]==0):
                bool_list.append(True)
                print(i)
            if (mat1_arr[i]!=0 and mat2_arr[i]!=0):
                new_sca=(mat1_arr[i])/(mat2_arr[i])
                if (np.isclose(possible_scalar.imag,new_sca.imag,rtol=1e-02) and np.isclose(possible_scalar.real,new_sca.real,rtol=1e-05)):
                    bool_list.append(True)
                    print(i)
        self.assertEqual([True]*mat1.size, bool_list,"it is working")
        
    def test_circ4(self):
        """Identity gates are like 'wait' commands.
        They should never be optimized (even without barriers).
        See: https://github.com/Qiskit/qiskit-terra/issues/2373
        """
        qc=QuantumCircuit(3)
        qc.h(0)
        qc.cx(0,1)
        qc.cx(0,2)
        qc.y(2)
        qc.z(1)
        qc.x(1)
#         qc.cu3(0.2,0.3,0.4,0,1)
        
        #convert to zx circuit
        simulator = Aer.get_backend('aer_simulator')
        qc1 = transpile(qc, simulator,optimization_level=0,basis_gates=['u3','cx'])

        g=zx.qasm(qc1.qasm())
        mat1=get_unitary_matrix(qc1)
        d=zx_to_dag(g)
        
        qc2=dag_to_circuit(d)

        mat2=get_unitary_matrix(qc2)
        
        mat1_arr = np.reshape(mat1,mat1.size)
        mat2_arr = np.reshape(mat2,mat2.size)
        first_non_zero_ind = (mat1_arr!=0).argmax(axis=0)
        bool_list=[True]*len(range(first_non_zero_ind))
        possible_scalar = (mat1_arr[first_non_zero_ind])/(mat2_arr[first_non_zero_ind])
        for i in range(mat1_arr.size):
            if (mat1_arr[i]==0 and mat2_arr[i]==0):
                bool_list.append(True)
                print(i)
            if (mat1_arr[i]!=0 and mat2_arr[i]!=0):
                new_sca=(mat1_arr[i])/(mat2_arr[i])
                if (np.isclose(possible_scalar.imag,new_sca.imag,rtol=1e-20) and np.isclose(possible_scalar.real,new_sca.real,rtol=1e-20)):
                    bool_list.append(True)
                    print(i)
        self.assertEqual([True]*mat1.size, bool_list,"it is working")
        
    def test_circ1(self):
        """Identity gates are like 'wait' commands.
        They should never be optimized (even without barriers).
        See: https://github.com/Qiskit/qiskit-terra/issues/2373
        """
        qc=QuantumCircuit(4)
        qc.ccz(0,1,2)
        qc.h(1)
        qc.t(1)
        qc.ccz(0,1,2)
        qc.h(1)
        qc.t(0)
        qc.ccz(2,1,0)
        qc.s(1)
        qc.ccx(2,1,0)
        qc.crz(0.2,0,1)
        qc.rccx(2,1,0)
        qc.cry(0.4,2,1)
        qc.ch(0,1)
        qc.rcccx(3,1,2,0)

        #convert to zx circuit
        simulator = Aer.get_backend('aer_simulator')
        qc1 = transpile(qc, simulator,optimization_level=0,basis_gates=['u3','cx'])

        g=zx.qasm(qc1.qasm())
        mat1=get_unitary_matrix(qc1)
        d=zx_to_dag(g)

        qc2=dag_to_circuit(d)

#         mat2=get_unitary_matrix(qc2)
        qc2.save_unitary()
        result = simulator.run(qc2).result()
        mat2 = np.asarray(result.get_unitary(qc2))
#         bool_list = matrix_equality(mat1,mat2)

        mat1_arr = np.reshape(mat1,mat1.size)
        mat2_arr = np.reshape(mat2,mat2.size)
        first_non_zero_ind = (mat1_arr!=0).argmax(axis=0)
        bool_list=[True]*len(range(first_non_zero_ind))
        possible_scalar = (mat1_arr[first_non_zero_ind])/(mat2_arr[first_non_zero_ind])
        for i in range(mat1_arr.size):
            if (mat1_arr[i]==0 and mat2_arr[i]==0):
                bool_list.append(True)
            if (mat1_arr[i]!=0 and mat2_arr[i]!=0):
                new_sca=(mat1_arr[i])/(mat2_arr[i])
                if (np.isclose(possible_scalar.imag,new_sca.imag,rtol=1e-15) and np.isclose(possible_scalar.real,new_sca.real,rtol=1e-08)):
                    bool_list.append(True)   

        self.assertEqual([True]*mat1.size, bool_list,"it is working")
        
    def test_circ2(self):
        """Identity gates are like 'wait' commands.
        They should never be optimized (even without barriers).
        See: https://github.com/Qiskit/qiskit-terra/issues/2373
        """
        qc=QuantumCircuit(4)
        qc.swap(0,1)
        qc.swap(1,2)
        qc.ccz(0,1,2)
        qc.h(1)
        qc.t(1)
        qc.ccz(0,1,2)
        qc.h(1)
        qc.t(0)
        qc.ccz(2,1,0)
        qc.cswap(1,2,3)
        qc.s(1)
        qc.ccx(2,1,0)
        qc.crz(0.2,0,1)
        qc.rccx(2,1,0)
        qc.cry(0.4,2,1)
        qc.ch(0,1)
        qc.rcccx(3,1,2,0)

        #convert to zx circuit
        simulator = Aer.get_backend('aer_simulator')
        qc1 = transpile(qc, simulator,optimization_level=0,basis_gates=['u3','cx'])

        g=zx.qasm(qc1.qasm())
        mat1=get_unitary_matrix(qc1)
        d=zx_to_dag(g)

        qc2=dag_to_circuit(d)

        mat2=get_unitary_matrix(qc2)

        mat1_arr = np.reshape(mat1,mat1.size)
        mat2_arr = np.reshape(mat2,mat2.size)
        first_non_zero_ind = (mat1_arr!=0).argmax(axis=0)
        bool_list=[True]*len(range(first_non_zero_ind))
        possible_scalar = (mat1_arr[first_non_zero_ind])/(mat2_arr[first_non_zero_ind])
        for i in range(mat1_arr.size):
            if (mat1_arr[i]==0 and mat2_arr[i]==0):
                bool_list.append(True)
            if (mat1_arr[i]!=0 and mat2_arr[i]!=0):
                new_sca=(mat1_arr[i])/(mat2_arr[i])
                if (np.isclose(possible_scalar.imag,new_sca.imag) and np.isclose(possible_scalar.real,new_sca.real)):
                    bool_list.append(True) 

        self.assertEqual(bool_list,[True]*mat1.size,"it is working")    

In [34]:
t1=TestZXtoDAG()

In [35]:
t1.test_GHZ()

y2
HAD(0)
CNOT(0,1)
CNOT(0,2)
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63


In [36]:
t1.test_circ4()

y2
HAD(0)
CNOT(0,1)
Z(1)
CNOT(0,2)
Z(2)
NOT(2)
NOT(1)
0
1
14
15
18
19
28
29
36
37
42
43
54
55
56
57


AssertionError: Lists differ: [True[85 chars] True, True, True, True, True, True, True, Tru[243 chars]True] != [True[85 chars] True]

First list contains 48 additional elements.
First extra element 16:
True

  [True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
   True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
-  True,
   True] : it is working

In [37]:
t1.test_circ2()

y1
CNOT(1,3)
CNOT(3,1)
CNOT(1,3)
CNOT(0,2)
CNOT(2,0)
CNOT(0,2)
HAD(3)
HAD(2)
HAD(0)
HAD(0)
CZ(0,2)
HAD(2)
ZPhase(2,phase=5/4)
HAD(2)
CZ(0,3)
CZ(0,2)
ZPhase(0,phase=5/4)
HAD(3)
HAD(0)
CZ(2,3)
CZ(0,3)
ZPhase(3,phase=5/4)
HAD(3)
HAD(2)
CZ(2,3)
ZPhase(2,phase=1/4)
HAD(2)
CNOT(2,0)
ZPhase(2,phase=1/4)
HAD(2)
CNOT(2,0)
CNOT(0,3)
HAD(2)
ZPhase(2,phase=7/4)
HAD(2)
CNOT(2,0)
HAD(2)
ZPhase(2,phase=1/4)
HAD(2)
CNOT(2,0)
CNOT(0,3)
ZPhase(2,phase=1/4)
HAD(2)
CNOT(2,3)
HAD(2)
ZPhase(2,phase=1/4)
HAD(2)
CNOT(2,0)
CNOT(0,3)
HAD(2)
ZPhase(2,phase=299776445/233865812)
HAD(2)
HAD(3)
HAD(0)
CZ(2,3)
CZ(0,3)
ZPhase(3,phase=1/4)
ZPhase(0,phase=7/4)
HAD(1)
HAD(3)
HAD(0)
HAD(2)
CZ(2,3)
CZ(1,2)
CZ(0,2)
ZPhase(2,phase=5/4)
HAD(2)
CZ(1,2)
HAD(1)
CNOT(1,3)
CZ(1,2)
ZPhase(1,phase=1/4)
HAD(1)
CZ(2,3)
CZ(1,2)
ZPhase(2,phase=7/4)
HAD(2)
HAD(3)
CZ(2,3)
CZ(1,3)
ZPhase(3,phase=3/4)
HAD(3)
HAD(1)
CZ(1,3)
CZ(0,1)
ZPhase(1,phase=1/4)
HAD(1)
CNOT(1,2)
ZPhase(1,phase=7/4)
HAD(1)
CNOT(1,2)
ZPhase(0,phase=5/4)
HAD(0)
CNOT(0,2)


AssertionError: Lists differ: [True[253 chars] True] != [True[253 chars] True, True, True, True, True, True, True, Tru[1227 chars]True]

Second list contains 212 additional elements.
First extra element 44:
True

Diff is 2304 characters long. Set self.maxDiff to None to see it. : it is working

In [38]:
from qiskit import QuantumCircuit
from qiskit.quantum_info import Clifford

# Bell state generation circuit
qc = QuantumCircuit(3)
qc.h(0)
qc.cx(2,0)
cliff = Clifford(qc)

In [39]:
print(cliff)

Clifford: Stabilizer = ['+IIX', '+IZI', '+ZII'], Destabilizer = ['+ZIZ', '+IXI', '+XIX']


In [40]:
??zx.optimize.permutation_as_swaps

In [41]:
import ZX_to_DAG

In [42]:
qc=QuantumCircuit(4)
# qc.ccx(2,1,0)
# qc.ccz(0,1,2)
qc.h(1)
# qc.ccx(1,2,3)
qc.t(1)
# qc.ccz(0,1,2)
qc.h(1)
qc.t(0)
# qc.ccz(2,1,0)
qc.s(1)
# qc.ccx(2,1,0)
# qc.crz(0.2*np.pi,0,1)
qc.rz(0.8*np.pi,1)
# qc.rccx(2,1,0)
# qc.cry(0.4*np.pi,2,1)
# qc.crx(0.02*np.pi,2,0)
# qc.cu(30,40,50,20.0,2,3)
# qc.ch(0,1)
# qc.rcccx(3,1,2,0)

#convert to zx circuit
simulator = Aer.get_backend('aer_simulator')
qc1 = transpile(qc, simulator,optimization_level=0,basis_gates=['u3','cx'])

g=zx.qasm(qc1.qasm())
mat1=get_unitary_matrix(qc1)
d=zx_to_dag(g)
# g1 = g.to_graph()
# g1 = zx.extract_circuit(g1).to_basic_gates()
# g2=zx.optimize.basic_optimization(g1)
# qc2=ZX_to_DAG._zxcirc_to_qiskit_circ(g2) 
qc2=dag_to_circuit(d)

#         mat2=get_unitary_matrix(qc2)
qc2.save_unitary()
result = simulator.run(qc2).result()
mat2 = np.asarray(result.get_unitary(qc2))

y1
HAD(1)
ZPhase(1,phase=1/4)
HAD(1)
ZPhase(1,phase=13/10)
ZPhase(0,phase=1/4)


In [43]:
qc=QuantumCircuit(3)

In [44]:
# qc.

In [45]:
# qiskit.quantum_info.Clifford(qc1)

In [46]:
mat1

array([[ 0.60001176-0.70252351j,  0.        +0.j        ,
        -0.29099476-0.24853301j,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ],
       [ 0.        +0.j        ,  0.92103152-0.07248675j,
         0.        +0.j        , -0.030025  -0.38150375j,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ],
       [-0.030025  +0.38150375j, -0.        +0.j        ,
        -0.9

In [47]:
# np.linalg.det(mat1)

In [48]:
# np.linalg.det(mat2)

In [49]:
# mat1[:,1]

In [50]:
# mat2[:,1]

In [51]:
mat2

array([[-0.70252351-0.60001176j,  0.        -0.j        ,
        -0.24853301+0.29099476j,  0.        -0.j        ,
         0.        -0.j        ,  0.        -0.j        ,
         0.        -0.j        ,  0.        -0.j        ,
         0.        -0.j        ,  0.        -0.j        ,
         0.        -0.j        ,  0.        -0.j        ,
         0.        -0.j        ,  0.        -0.j        ,
         0.        -0.j        ,  0.        -0.j        ],
       [ 0.        -0.j        , -0.07248675-0.92103152j,
         0.        -0.j        , -0.38150375+0.030025j  ,
         0.        -0.j        ,  0.        -0.j        ,
         0.        -0.j        ,  0.        -0.j        ,
         0.        -0.j        ,  0.        -0.j        ,
         0.        -0.j        ,  0.        -0.j        ,
         0.        -0.j        ,  0.        -0.j        ,
         0.        -0.j        ,  0.        -0.j        ],
       [ 0.38150375+0.030025j  , -0.        +0.j        ,
        -0.0

In [75]:
??zx_to_dag

In [60]:
import ZX_to_DAG

In [61]:
qc=QuantumCircuit(4)
qc.ccx(2,1,0)
qc.ccz(0,1,2)
qc.h(1)
qc.ccx(1,2,3)
qc.t(1)
qc.ccz(0,1,2)
qc.h(1)
qc.t(0)
qc.ccz(2,1,0)
qc.s(1)
qc.ccx(2,1,0)
qc.crz(0.2*np.pi,0,1)
qc.rz(0.8*np.pi,1)
# qc.rccx(2,1,0)
# qc.cry(0.4*np.pi,2,1)
# qc.crx(0.02*np.pi,2,0)
# qc.cu(30,40,50,20.0,2,3)
# qc.ch(0,1)
# qc.rcccx(3,1,2,0)

In [62]:
g=zx.Circuit(4)

In [63]:
g.add_gate(zx.circuit.gates.Tofolli(2,1,0))

In [64]:
g.add_gate(zx.circuit.gates.CCZ(0,1,2))

In [65]:
g.add_gate(zx.circuit.gates.HAD(1))
g.add_gate(zx.circuit.gates.Tofolli(1,2,3))
g.add_gate(zx.circuit.gates.T(1))
g.add_gate(zx.circuit.gates.CCZ(0,1,2))
g.add_gate(zx.circuit.gates.HAD(1))
g.add_gate(zx.circuit.gates.T(0))
g.add_gate(zx.circuit.gates.CCZ(2,1,0))
g.add_gate(zx.circuit.gates.S(1))
g.add_gate(zx.circuit.gates.Tofolli(2,1,0))
g.add_gate(zx.circuit.gates.CRZ(0.2*np.pi,0,1))
g.add_gate(zx.circuit.gates.ZPhase(0.8*np.pi,1))

In [66]:
# g.to_qasm()

In [67]:
#convert to zx circuit
# simulator = Aer.get_backend('aer_simulator')
# qc1 = transpile(qc, simulator,optimization_level=0,basis_gates=['u3','cx'])

In [68]:
# mat1=get_unitary_matrix(qc1)
qc.save_unitary()
result = simulator.run(qc).result()
mat1 = np.asarray(result.get_unitary(qc))

g=zx.qasm(qc.qasm())
g1 = g.to_graph()
zx.simplify.full_reduce(g1)
g1 = zx.extract_circuit(g1).to_basic_gates()
n=g1.qubits
qc2=QuantumCircuit(n)
for g in g1.gates:
    print(g)
    if g.name == 'SWAP':
        qc2.swap(g.control,g.target)
    if g.name == 'HAD':
        qc2.h(g.target)
    if g.name == 'ZPhase':
        qc2.rz(g.phase*np.pi,g.target)
    if g.name == 'CZ':
        qc2.cz(g.control, g.target)
    if g.name == 'CNOT':
        qc2.cx(g.control, g.target)
    if g.name == 'S':
        qc2.rz(g.phase*np.pi, g.target)
    if g.name == 'T':
        qc2.rz(g.phase*np.pi, g.target)
    if g.name == 'XPhase':
        qc2.rx(g.phase*np.pi, g.target) 
    if g.name == 'CCZ':
        qc2.ccz(g.ctrl1,g.ctrl2,g.target)
    if g.name=='CHAD':
        qc2.ch(g.control,g.target)
    if g.name == 'CRZ':
        qc2.crz(g.control,g.target,g.phase)
    if g.name=='Tof':
        qc2.ccx(g.ctrl1,g.ctrl2,g.target) 
qc2.save_unitary()
result = simulator.run(qc2).result()
mat2 = np.asarray(result.get_unitary(qc2))

Simulation failed and returned the following error message:
ERROR:  [Experiment 0] Circuit circuit-318 contains invalid instructions {"instructions": {save_unitary}, "gates": {crz, ccz}} for "statevector" method.


QiskitError: 'Data for experiment "circuit-318" could not be found.'

In [69]:
mat1.round(3)

array([[ 0.6  -0.703j,  0.   +0.j   , -0.291-0.249j,  0.   +0.j   ,
         0.   +0.j   ,  0.   +0.j   ,  0.   +0.j   ,  0.   +0.j   ,
         0.   +0.j   ,  0.   +0.j   ,  0.   +0.j   ,  0.   +0.j   ,
         0.   +0.j   ,  0.   +0.j   ,  0.   +0.j   ,  0.   +0.j   ],
       [ 0.   +0.j   ,  0.921-0.072j,  0.   +0.j   , -0.03 -0.382j,
         0.   +0.j   ,  0.   +0.j   ,  0.   +0.j   ,  0.   +0.j   ,
         0.   +0.j   ,  0.   +0.j   ,  0.   +0.j   ,  0.   +0.j   ,
         0.   +0.j   ,  0.   +0.j   ,  0.   +0.j   ,  0.   +0.j   ],
       [-0.03 +0.382j, -0.   +0.j   , -0.921-0.072j, -0.   +0.j   ,
        -0.   +0.j   , -0.   +0.j   , -0.   +0.j   , -0.   +0.j   ,
        -0.   +0.j   , -0.   +0.j   , -0.   +0.j   , -0.   +0.j   ,
        -0.   +0.j   , -0.   +0.j   , -0.   +0.j   , -0.   +0.j   ],
       [-0.   +0.j   , -0.291+0.249j, -0.   +0.j   , -0.6  -0.703j,
        -0.   +0.j   , -0.   +0.j   , -0.   +0.j   , -0.   +0.j   ,
        -0.   +0.j   , -0.   +0.j   , -0.   +

In [70]:
mat2.round(3)

array([[-0.703-0.6j  ,  0.   -0.j   , -0.249+0.291j,  0.   -0.j   ,
         0.   -0.j   ,  0.   -0.j   ,  0.   -0.j   ,  0.   -0.j   ,
         0.   -0.j   ,  0.   -0.j   ,  0.   -0.j   ,  0.   -0.j   ,
         0.   -0.j   ,  0.   -0.j   ,  0.   -0.j   ,  0.   -0.j   ],
       [ 0.   -0.j   , -0.072-0.921j,  0.   -0.j   , -0.382+0.03j ,
         0.   -0.j   ,  0.   -0.j   ,  0.   -0.j   ,  0.   -0.j   ,
         0.   -0.j   ,  0.   -0.j   ,  0.   -0.j   ,  0.   -0.j   ,
         0.   -0.j   ,  0.   -0.j   ,  0.   -0.j   ,  0.   -0.j   ],
       [ 0.382+0.03j , -0.   +0.j   , -0.072+0.921j, -0.   +0.j   ,
        -0.   +0.j   , -0.   +0.j   , -0.   +0.j   , -0.   +0.j   ,
        -0.   +0.j   , -0.   +0.j   , -0.   +0.j   , -0.   +0.j   ,
        -0.   +0.j   , -0.   +0.j   , -0.   +0.j   , -0.   +0.j   ],
       [-0.   +0.j   ,  0.249+0.291j, -0.   +0.j   , -0.703+0.6j  ,
        -0.   +0.j   , -0.   +0.j   , -0.   +0.j   , -0.   +0.j   ,
        -0.   +0.j   , -0.   +0.j   , -0.   +